// Generated by CoffeeScript 1.3.3
(function() {

  div({
    "class": 'editor'
  }, function() {
    return textarea({
      cols: 1,
      rows: 20
    });
  });

  div({
    "class": 'toolbar'
  }, function() {
    div(a({
      "class": 'pull-right btn btn-info btn-large',
      href: 'view'
    }, function() {
      return 'view';
    }));
    return div(a({
      "class": 'pull-right btn btn-success btn-large',
      href: 'test'
    }, function() {
      return 'test';
    }));
  });

}).call(this);
