// Generated by CoffeeScript 1.3.3
(function() {
  var coffeekup;

  global.port = process.env.PORT || 3000;

  coffeekup = require('coffeekup');

  app.configure(function() {
    this.use(express["static"](__dirname + '/public'));
    this.set("views", __dirname + '/views');
    this.set('view engine', 'coffee');
    return this.register('.coffee', coffeekup.adapters.express);
  });

  app.get("/", function(req, res) {
    return res.render('home');
  });

  app.get("/test", function(req, res) {
    return res.render('test');
  });

}).call(this);
