// Generated by CoffeeScript 1.3.3
(function() {

  this.MethodMatcher = (function() {

    function MethodMatcher() {}

    MethodMatcher.prototype.match = function(sut, step) {
      var _ref;
      this.sut = sut;
      this.step = step;
      return (_ref = this.literal()) != null ? _ref : this.regex();
    };

    MethodMatcher.prototype.literal = function() {
      if (this.sut[this.step] != null) {
        return this.sut[this.step];
      }
    };

    MethodMatcher.prototype.regex = function() {
      var method;
      for (method in this.sut) {
        if (this.step.match(method)) {
          return this.sut[method];
        }
      }
    };

    return MethodMatcher;

  })();

}).call(this);
