// Generated by CoffeeScript 1.3.3
(function() {

  global.express = require('express');

  global.app = express.createServer();

  require('./config');

  app.listen(port);

  console.log("Giant Leapin' Lizards!");

}).call(this);
