// Generated by CoffeeScript 1.3.3
(function() {
  var StepArgsParser;

  StepArgsParser = require('./args_parser').StepArgsParser;

  this.StepParser = (function() {

    function StepParser(steps) {
      this.steps = steps;
      this.args = new StepArgsParser;
    }

    StepParser.prototype.parse = function(line) {
      return this.steps.push({
        title: line,
        name: this.args.normalized(line),
        args: this.args.parse(line)
      });
    };

    return StepParser;

  })();

}).call(this);
