// Generated by CoffeeScript 1.3.3
(function() {

  require('./settings');

  engine.configure(function() {
    return engine.use(express.bodyParser());
  });

  require('./root');

  require('./runner/controller');

}).call(this);
