// Generated by CoffeeScript 1.3.3
(function() {
  var Login, Parser, Runner;

  Parser = require('./parsers/parser').Parser;

  Runner = require('./runner/runner').Runner;

  Login = require('../../examples/fixtures/login').Login;

  this.EngineService = (function() {

    function EngineService() {
      this.parser = new Parser;
      this.runner = new Runner;
      this.sut = new Login;
    }

    EngineService.prototype.run = function(test) {
      return this.runner.run_steps(this.sut, this.parser.parse(test));
    };

    return EngineService;

  })();

}).call(this);
