// Generated by CoffeeScript 1.3.3
(function() {

  global.chipojos = '    _    _            _\n __| |_ (_)_ __  ___ (_)___ ___\n/ _| \' \\| | \'_ \\/ _ \\| / _ (_-<\n\\__|_||_|_| .__/\\___// \\___/__/\n          |_|      |__/';

  global.engine_port = process.env.ENGINE_PORT || 3001;

  global.engine_uri = "http://localhost:" + engine_port;

}).call(this);
