// Generated by CoffeeScript 1.3.3
(function() {
  var EngineService;

  EngineService = require('../service').EngineService;

  engine.post('/run', function(req, res) {
    var service, test;
    service = new EngineService;
    test = req.body.content;
    return res.send(service.run(test));
  });

}).call(this);
